# Project
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-25.0.2.10-hotspot
org.gradle.user.home=D:\\_Modding\\.gradle
version=2.6
group=io.github.maplemods.sapling
java_version=25

# Common
minecraft_version=26.2
minecraft_full_version=26.2.0
mod_name=Sapling
mod_author=MapleMods
mod_id=sapling
license=All Rights Reserved
credits=
description=A Minecraft mod library that powers MapleMods.
minecraft_version_range=[26.2]

## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# https://fabricmc.net/develop/
fabric_version=0.154.0+26.2
fabric_loader_version=0.19.3

# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=65.0.3
forge_loader_version_range=[65,)

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.2.0.8-beta
neoforge_loader_version_range=[4,)

# https://maven.blamejared.com/mysticdrew/
common_networking_version=26.2-1.1.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false