# Project
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.10.7-hotspot
version=2.2
group=io.github.maplemods.sapling
java_version=21

# Common
minecraft_version=1.21.11
mod_name=Sapling
mod_author=MapleMods
mod_id=sapling
license=All Rights Reserved
credits=
description=A Minecraft mod library that powers MapleMods.
minecraft_version_range=[1.21.11]

## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050

# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# https://fabricmc.net/develop/
fabric_version=0.140.0+1.21.11
fabric_loader_version=0.18.2

# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=61.0.3
forge_loader_version_range=[61,)

# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.11.10-beta
neoforge_loader_version_range=[4,)

# common-networking
common_networking_version=1.0.22

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false